<?php

namespace Database\Seeders\Prerequisite;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use MongoDB\BSON\ObjectID;

class Subjects extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('subjects')->insert([
            [
                '_id'      => 1,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'Math',
                'user_id'  => 3,
                'level_id' => 10,
                'code'    => 'Math7',
                'description' => 'Mathematics',
                'lab'    => 0,
                'lec'    => 3,
                'units'  => 3,
                'is_major' => false,
                'syllabus' => json_decode('[
                    {
                        "chapter":"I",
                        "titles":[
                            "Definition of Data Structure and algorithm",
                            "Abstraction",
                            "Data abstraction and Abstract Data Types (ADTs)",
                            "Characteristics of Data Structures",
                            "Categories of Data Structures"
                        ]
                    }]'
                )
            ],  
            [
                '_id'      => 2,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'English',
                'user_id'  => 3,
                'level_id' => 10,
                'code'    => 'Eng7',
                'description' => 'English',
                'lab'  => 0,
                'lec'  => 3,
                'units'  => 3,
                'is_major' => false,
                'syllabus' => 'Pending syllabus',
            ], 
            [
                '_id'      => 3,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'Filipino 7',
                'user_id'  => 3,
                'level_id' => 10,
                'code'    => 'Fil7',
                'description'    => 'Filipino',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major' => false,
                'syllabus' => 'Pending syllabus',
            ],  
            [
                '_id'      => 4,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'Edukasyon Sa Pagkakatao',
                'user_id'  => 3,
                'level_id' => 10,
                'code'    => 'ESP7',
                'description'    => 'ESP',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => false,
                'syllabus' => 'Pending syllabus',
            ],  
            [
                '_id'      => 5,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'Araling Panglipunan',
                'user_id'  => 3,
                'level_id' => 10,
                'code'    => 'AP7',
                'description'    => 'AP',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => false,
                'syllabus' => 'Pending syllabus',
            ],  
            [
                '_id'      => 6,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'Science 7',
                'user_id'  => 3,
                'level_id' => 10,
                'code'    => 'Sci7',
                'description'    => 'Science',
                'lab'    => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => false,
                'syllabus' => 'Pending syllabus',
            ], 
            [
                '_id'      => 7,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'MAPEH',
                'user_id'  => 3,
                'level_id' => 10,
                'code'    => 'MAPEH7',
                'description'    => 'MAPEH',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => false,
                'syllabus' => 'Pending syllabus',
            ],   
            [
                '_id'      => 8,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'Technology Livelyhood Education',
                'user_id'  => 3,
                'level_id' => 10,
                'code'    => 'TLE7',
                'description'    => 'TLE',
                'lab'   => 0,
                'lec'   => 3,
                'units' => 3,
                'is_major'  => false,
                'syllabus' => 'Pending syllabus',
            ],
            [
                '_id'      => 9,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'Mathematics 8',
                'user_id'  => 3,
                'level_id' => 11,
                'code'    => 'Math8',
                'description'    => 'Mathematics',
                'lab'    => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major' => false,
                'syllabus' => 'Pending syllabus',
            ],  
            [
                '_id'      => 10,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'English',
                'user_id'  => 3,
                'level_id' => 11,
                'code'    => 'Eng8',
                'description'    => 'English',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => false,
                'syllabus' => 'Pending syllabus',
            ], 
            [
                '_id'      => 11,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'Fil',
                'user_id'  => 3,
                'level_id' => 11,
                'code'    => 'Fil8',
                'description'    => 'Filipino',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major' => false,
                'syllabus' => 'Pending syllabus',
            ],  
            [
                '_id'      => 12,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'ESP',
                'user_id'  => 3,
                'level_id' => 11,
                'code'    => 'ESP8',
                'description'    => 'ESP',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major' => false,
                'syllabus' => 'Pending syllabus',
            ],  
            [
                '_id'      => 13,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'AP',
                'user_id'  => 3,
                'level_id' => 11,
                'code'    => 'AP8',
                'description'    => 'AP',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major' => false,
                'syllabus' => 'Pending syllabus',
            ],  
            [
                '_id'      => 14,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'Sci',
                'user_id'  => 3,
                'level_id' => 11,
                'code'    => 'Sci8',
                'description'    => 'Science',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major' => false,
            ], 
            [
                '_id'      => 15,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'MAPEH',
                'user_id'  => 3,
                'level_id' => 11,
                'code'    => 'MAPEH8',
                'description'    => 'MAPEH',
                'lab'  => 0,
                'lec'  => 1,
                'units'    => 3,
                'is_major'  => false,
            ],   
            [
                '_id'      => 16,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'TLE',
                'user_id'  => 3,
                'level_id' => 11,
                'code'    => 'TLE8',
                'description'    => 'TLE',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => false,
            ],
            [
                '_id'      => 17,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'Math',
                'user_id'  => 3,
                'level_id' => 12,
                'code'    => 'Math9',
                'description'    => 'Mathematics',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => false,
            ],  
            [
                '_id'      => 18,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'English',
                'user_id'  => 3,
                'level_id' => 12,
                'code'    => 'Eng9',
                'description'    => 'English',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => false,
            ], 
            [
                '_id'      => 19,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'Fil',
                'user_id'  => 3,
                'level_id' => 12,
                'code'    => 'Fil9',
                'description'    => 'Filipino',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => false,
            ],  
            [
                '_id'      => 20,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'ESP',
                'user_id'  => 3,
                'level_id' => 12,
                'code'    => 'ESP9',
                'description'=> 'ESP',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => false,
            ],  
            [
                '_id'      => 21,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'AP',
                'user_id'  => 3,
                'level_id' => 12,
                'code'    => 'AP9',
                'description'    => 'AP',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => false,
            ],  
            [
                '_id'      => 22,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'Sci',
                'user_id'  => 3,
                'level_id' => 12,
                'code'    => 'Sci9',
                'description'    => 'Science',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => false,
            ], 
            [
                '_id'      => 23,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'MAPEH',
                'user_id'  => 3,
                'level_id' => 12,
                'code'    => 'MAPEH9',
                'description'    => 'MAPEH',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => false,
            ],   
            [
                '_id'      => 24,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'TLE',
                'user_id'  => 3,
                'level_id' => 12,
                'code'    => 'TLE9',
                'description' => 'TLE',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => false,
            ],
            [
                '_id'      => 25,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'Training',
                'user_id'  => 3,
                'level_id' => 12,
                'code'    => 'SPS',
                'description'    => 'Special Program in Sports',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => true,
            ],  
            [
                '_id'      => 26,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'Pre calculus',
                'user_id'  => 3,
                'level_id' => 14,
                'code'    => 'Pre cal',
                'description'    => 'pre calculus',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => true,
            ],  
            [
                '_id'      => 28,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'Gen math',
                'user_id'  => 3,
                'level_id' => 15,
                'code'    => 'GenMath',
                'description'    => 'General Mathematics',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => true,
                'strand'   => '60264978b22e00009a006436',
            ],  
            [
                '_id'      => 29,
                'school_id' => '60264978b22e00009a006436',
                'name'     => 'Research&chemestry',
                'user_id'  => 3,
                'level_id' => 10,
                'code'    => 'STE9',
                'description'    => 'Research and Chemestry',
                'lab'  => 0,
                'lec'  => 3,
                'units'    => 3,
                'is_major'  => true,
            ],  
        ]);
    }
}
